name: Generate pacman animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Light 버전 생성
      - name: Generate pacman-contribution-graph.svg (light)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: light
          output: dist/pacman-contribution-graph.svg

      # Dark 버전 생성
      - name: Generate pacman-contribution-graph-dark.svg (dark)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: dark
          output: dist/pacman-contribution-graph-dark.svg

      - name: Push SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          commit_message: "update pacman ${{ github.run_id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
